baseURL = "https://furs.trackmania.xyz/"
languageCode = "en-us"
title = "Trackmania Furs"
theme = "hugo-scroll"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
    copyright = "[Trackmania Furs](https://gitlab.com/TMFurs) © CC-BY-4.0"
    credits = "Website developed by [DergnNamedSkye](https://oshiro.xyz)"
    description = "Website dedicated to \"Trackmania Furs\" community"
    favicon = "images/favicon.webp"
    images = ["images/general/cover.jpg"]
    title = "Trackmania Furs — Furry Community in Trackmania"
    [params.meta]
        keywords = "gaming, racing, arcade, trackmania, club, furry"
